[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
    "cd ../.. && npm install",
    "cd ../.. && npm run build -w shared-types"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve dist -s -l 5173"

